language: python
install:
- pip install mkdocs pymdown-extensions
script:
- git clean -f -d -x
after_success:
- git config user.name "Bastien Guyl"
- git config user.email "bastien@guyl.me"
- git remote add gh-token "https://${github_token}@github.com/EEVCOM-Montpellier/hmax-documentation.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name gh-token;